@echo off
echo Starting WorkConnect with Default Trending Skills...
cd backend
echo Seeding trending skills data...
python seed_default_trending_skills.py
echo Starting backend server...
python app.py